Remove "use strict" due to WebKit bug(probably)
I have found that an unknown condition causes an error for variables declared with "const".

error: SyntaxError: Can't create duplicate variable: <variable>

Maybe related?: https://stackoverflow.com/questions/40091136/cant-create-duplicate-variable-that-shadows-a-global-property and https://github.com/Cizzuk/CSE/issues/12